print("64")

# 維護二的冪次
print("ADD b d c c")
print("ADD b e d d")
print("ADD b f e e")
print("ADD b g f f")
print("ADD b h g g")
print("ADD b i h h")
print("ADD b j i i")
print("ADD b k j j")
print("ADD b l k k")
print("ADD b m l l")
print("ADD b n m m")
print("ADD b o n n")
print("ADD b p o o")
print("ADD b q p p")
print("ADD b r q q")
print("ADD b s r r")

# z = 0, 用來記錄答案
print("SUB b z c c") 

# 處理 >= 的問題
print("ADD b a a b")

# 
print("LES y r a")
print("ADD y z z q")
print("SUB y a a r")

print("LES y q a")
print("ADD y z z p")
print("SUB y a a q")

print("LES y p a")
print("ADD y z z o")
print("SUB y a a p")

print("LES y o a")
print("ADD y z z n")
print("SUB y a a o")

print("LES y n a")
print("ADD y z z m")
print("SUB y a a n")
print("LES y m a")
print("ADD y z z l")
print("SUB y a a m")
print("LES y l a")
print("ADD y z z k")
print("SUB y a a l")
print("LES y k a")
print("ADD y z z j")
print("SUB y a a k")
print("LES y j a")
print("ADD y z z i")
print("SUB y a a j")
print("LES y i a")
print("ADD y z z h")
print("SUB y a a i")
print("LES y h a")
print("ADD y z z g")
print("SUB y a a h")
print("LES y g a")
print("ADD y z z f")
print("SUB y a a g")
print("LES y f a")
print("ADD y z z e")
print("SUB y a a f")
print("LES y e a")
print("ADD y z z d")
print("SUB y a a e")
print("LES y d a")
print("ADD y z z c")

# 處理 >= 的問題
print("SUB y a a d")
print("MOV b a z")